### ISSUE TITLE
无法正确安装catalina

### ISSUE THREAD

**Issue by XiaojunXie** [wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh#1]
pull你15.1.1-release那个branch
然后安装，显示power supply unavailable
我的系统是gaming x + 9600k + 5700 xt
请问你bios怎么设置的，然后是不是我只需要留一些特定的文件并不需要全部留着？

**Comment by wqh0109663** [comment]
BIOS的截图我刚才加在了screen shot文件夹下了自己看下 如果主板和U跟我的一样的话 应该是直接用我的efi就可以了 下载的话 建议你用release里面的

**Comment by Arnult** [comment]
老哥我也是z390 gaming x和9600k，用你的efi，安装跑完代码就自动重启了

**Comment by wqh0109663** [comment]
> 老哥我也是z390 gaming x和9600k，用你的efi，安装跑完代码就自动重启了
试试在bios按照 Windows 8/10 设置为other，csm support 设置为disable，secure boot设置为disabled，peripherals里面 initial display 设置为pcie 1 slot，power 里面erp设置为enabled，然后把internal graphics设置为enabled，然后就是超频的设置，看你个人喜好了，我是cpu设置的47，然后内存条是2666，打开xmp了，按照我这种百分百可以进去

**Comment by wqh0109663** [comment]
@Arnult

**Comment by wqh0109663** [comment]
其他的默认就好了

**Comment by Arnult** [comment]
谢谢老哥回复，bios我安照你设了但还是有报错





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HuanZi <notifications@github.com&gt;
发送时间: 2019年12月28日 17:24
收件人: wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh <Gigabyte-Z390-Gaming-X-Hackintosh@noreply.github.com&gt;
抄送: Arnult <275300180@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh] 无法正确安装catalina (#1)




其他的默认就好了

**Comment by Arnult** [comment]
谢谢您，我把独显装上就好了------------------ 原始邮件 ------------------
发件人: "HuanZi"<notifications@github.com>
发送时间: 2019年12月28日(星期六) 下午5:24
收件人: "wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh"<Gigabyte-Z390-Gaming-X-Hackintosh@noreply.github.com>;
抄送: "Arnult"<275300180@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh] 无法正确安装catalina (#1)



其他的默认就好了
 
&mdash;
