### ISSUE TITLE
big sur的clover不搞了吗？

### ISSUE THREAD

**Issue by Arnult** [wqh0109663/Gigabyte-Z390-Gaming-X-Hackintosh#4]

**Comment by wqh0109663** [comment]
正式版的都没发布

**Comment by Arnult** [comment]
咱们这主板怎么搞cfg lock

**Comment by wqh0109663** [comment]
那个啥 没看到 你搞定了吗啊 如果没有 下面给个链接 具体在哪里你搜一下就好了 文档在https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html#prerequisites

**Comment by wqh0109663** [comment]
注意先备份BIOS

**Comment by Arnult** [comment]
我用openCore搞定了，升级bios就是有cfg lock开关了

**Comment by luhua98989898** [comment]
这个oc可以引导big sur吗？同款配置

**Comment by Arnult** [comment]
> 这个oc可以引导big sur吗？同款配置

可以，我是把bios升级了关了cfg就行，你去搜搜这款主板设置都差不多
